name: Deploy runner to VPS

on:
  push:
    branches: [ main ]
    paths:
      - 'n8n-runner/**'
      - 'local-files/**'
      - '.github/workflows/deploy-runner.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.VPS_PORT }}" -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure dirs on VPS
        run: |
          ssh -p "${{ secrets.VPS_PORT }}" ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /opt/n8n-runner /local-files/runner /local-files/data"

      - name: Rsync repo → VPS
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.VPS_PORT }}" n8n-runner/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/opt/n8n-runner/
          rsync -avz --delete -e "ssh -p ${{ secrets.VPS_PORT }}" local-files/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/local-files/

      - name: Ensure .env on VPS
        run: |
          ssh -p "${{ secrets.VPS_PORT }}" ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            mkdir -p /opt/n8n-runner && \
            umask 177 && \
            printf '%s\n' \
              'ALURA_USER=${{ secrets.ALURA_USER }}' \
              'ALURA_PASS=${{ secrets.ALURA_PASS }}' \
              'LINKEDIN_USER=${{ secrets.LINKEDIN_USER }}' \
              'LINKEDIN_PASS=${{ secrets.LINKEDIN_PASS }}' \
              > /opt/n8n-runner/.env && \
            chmod 600 /opt/n8n-runner/.env
          "

      - name: Build + up runner
        run: |
          ssh -p "${{ secrets.VPS_PORT }}" ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /opt/n8n-runner && docker compose --env-file /opt/n8n-runner/.env build runner && docker compose --env-file /opt/n8n-runner/.env up -d runner && docker compose --env-file /opt/n8n-runner/.env ps
          "
